### ISSUE TITLE
Erreur si dossier de sortie non-renseigné 

### ISSUE THREAD

**Issue by rmylb** [Team-SI-SIG/HistoricalMap#20]
_OS : Kubuntu 22.04
Version de Python : 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] 
Version de QGIS : 3.28.6-Firenze Firenze, 868c9fa03b_ 

Erreur lors de la selection du dossier de destination si l'on annule après le prompt de la fenêtre.

```
Une erreur est survenue lors de l'éxécution du code Python: 

TypeError: expected str, bytes or os.PathLike object, not tuple 
Traceback (most recent call last):
  File "/home/rle/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HistoricalMap/historical_map.py", line 269, in select_output_file
    fileName, fileExtension = os.path.splitext(fileName)
  File "usr/lib/python3.10/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not tuple


Version de Python : 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] 
Version de QGIS : 3.28.6-Firenze Firenze, 868c9fa03b 

Chemin Python :
/usr/share/qgis/python
/home/rle/.local/share/QGIS/QGIS3/profiles/default/python
/home/rle/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/local/lib/python3.10/dist-packages
/usr/lib/python3/dist-packages
/home/rle/.local/share/QGIS/QGIS3/profiles/default/python
```

**Comment by jmonticolo** [comment]
voir également #21
